---
kind: "Deployment"
apiVersion: "apps/v1"
metadata: 
  name: "goku-studio"
  namespace: "aios"
  labels: 
    app: "goku-studio"
spec: 
  replicas: 0
  selector: 
    matchLabels: 
      app: "goku-studio"
  template: 
    metadata: 
      creationTimestamp: null
      labels: 
        app: "goku-studio"
    spec: 
      containers: 
        - 
          name: "goku-studio"
          image: "275106820702.dkr.ecr.ap-northeast-1.amazonaws.com/cto/goku-studio:qa-202606121708-9458c6be"

